language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag udagram-api-feed avoorhees2534/udagram-api-feed:latest
  - docker tag udagram-api-user avoorhees2534/udagram-api-user:latest
  - docker tag udagram-frontend avoorhees2534/udagram-frontend:latest
  - docker tag reverseproxy avoorhees2534/reverseproxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push avoorhees2534/udagram-api-feed:latest
  - docker push avoorhees2534/udagram-api-user:latest
  - docker push avoorhees2534/udagram-frontend:latest
  - docker push avoorhees2534/reverseproxy:latest